name: waste_collection
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.13
  google_sign_in: ^5.2.3
  intl: ^0.17.0
  image_picker: ^0.8.4+9
  permission_handler: ^9.0.1
  http_parser: ^4.0.0
  flutter_switch: ^0.3.2
  flutter_login_facebook: ^1.4.1
  firebase_core: ^1.13.1
  firebase_messaging: ^11.2.8
  flutter_local_notifications: ^10.0.0-dev.1
  loading_indicator: ^3.0.3
  flutter_animated_dialog: ^2.0.1
  fluttertoast: ^8.0.9
  provider: ^6.0.2
  marquee: ^2.2.3
  jiffy: ^5.0.0
  flutter_datetime_picker: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/icons/
    - images/home/
    - images/input/
    - images/message/
    - images/profile/

  fonts:
    - family: DiodrumCyrillic
      fonts:
        - asset: fonts/DiodrumCyrillic-Bold.ttf
          weight: 700
        - asset: fonts/DiodrumCyrillic-semiBold.ttf
          weight: 600
        - asset: fonts/DiodrumCyrillic-Medium.ttf
          weight: 500
        - asset: fonts/DiodrumCyrillic-Regular.ttf
          weight: 400
