name: waste_collection
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  flutter_screenutil: ^5.1.1
  touchable_opacity: ^1.2.0
  shared_preferences: ^2.0.13
  google_sign_in: ^5.2.3
  firebase_auth: ^3.3.7
  intl: ^0.17.0
  image_picker: ^0.8.4+9
  permission_handler: ^9.0.1
  dio: ^4.0.4
  http_parser: ^4.0.0
  show_up_animation: ^2.0.0
  marquee: ^2.2.1
  flutter_switch: ^0.3.2
  flutter_login_facebook: ^1.4.1
  mime: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/icons/
    - images/home/
    - images/input/
    - images/message/
    - images/profile/

  fonts:
    - family: DiodrumCyrillic
      fonts:
        - asset: fonts/DiodrumCyrillic-Regular.ttf
    - family: DiodrumCyrillicBold
      fonts:
        - asset: fonts/DiodrumCyrillic-Bold.ttf
    - family: DiodrumCyrillicMedium
      fonts:
        - asset: fonts/DiodrumCyrillic-Medium.ttf
    - family: DiodrumCyrillicSemiBold
      fonts:
        - asset: fonts/DiodrumCyrillic-semiBold.ttf
